apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-auth
  template:
    metadata:
      labels:
        app: travel-auth
    spec:
      containers:
        - name: travel-auth
          image: kran891/travel-auth
          imagePullPolicy: Never
          env:
            - name: MONGO_URL
              value: mongodb://mongo-srv:27017/travel-agency-users
---
apiVersion: v1
kind: Service
metadata:
  name: travel-auth-srv
spec:
  selector:
    app: travel-auth
  ports:
    - name: auth-api
      protocol: TCP
      port: 4000
      targetPort: 4000
#inside while routing we need to use clusterIp name i:e comments-srv here